In [ ]:
import pandas as pd
import numpy as np
import os

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
import glob

# Path to the folder containing CSV files
path = "/content/drive/MyDrive/2.CSV Files/*.csv"

# Get a list of all CSV files in the folder
csv_files = glob.glob(path)

# Concatenate all CSV files
df = pd.concat([pd.read_csv(file) for file in csv_files], ignore_index=True)

# Save the concatenated DataFrame to a new CSV
df.to_csv("data.csv", index=False)

In [ ]:
df.to_csv("data.csv", index=False)

In [ ]:
data = pd.read_csv('data.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1950 entries, 0 to 1949
Data columns (total 81 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Original Url                    1852 non-null   object
 1   Address                         1950 non-null   object
 2   Content Type                    1845 non-null   object
 3   Status Code                     1950 non-null   int64
 4   Status                          1934 non-null   object
 5   Indexability                    1950 non-null   object
 6   Indexability Status             372 non-null    object
 7   Title 1                         1603 non-null   object
 8   Title 1 Length                  1950 non-null   int64
 9   Title 1 Pixel Width             1950 non-null   int64
 10  Title 2                         22 non-null     object
 11  Title 2 Length                  1180 non-null   float64
 12  Title 2 Pixel Width             1180 non-null   float64
 13  Meta Description 1              1207 non-null   object
 14  Meta Description 1 Length       1950 non-null   int64
 15  Meta Description 1 Pixel Width  1950 non-null   int64
 16  Meta Description 2              16 non-null     object
 17  Meta Description 2 Length       956 non-null    float64
 18  Meta Description 2 Pixel Width  956 non-null    float64
 19  Meta Keywords 1                 279 non-null    object
 20  Meta Keywords 1 Length          1950 non-null   int64
 21  H1-1                            1350 non-null   object
 22  H1-1 Length                     1950 non-null   int64
 23  H1-2                            274 non-null    object
 24  H1-2 Length                     1950 non-null   int64
 25  H2-1                            1302 non-null   object
 26  H2-1 Length                     1950 non-null   int64
 27  H2-2                            1107 non-null   object
 28  H2-2 Length                     1950 non-null   int64
 29  Meta Robots 1                   627 non-null    object
 30  Meta Robots 2                   30 non-null     object
 31  X-Robots-Tag 1                  11 non-null     object
 32  Meta Refresh 1                  4 non-null      object
 33  Canonical Link Element 1        1283 non-null   object
 34  rel="next" 1                    121 non-null    object
 35  rel="prev" 1                    7 non-null      object
 36  HTTP rel="next" 1               0 non-null      float64
 37  HTTP rel="prev" 1               0 non-null      float64
 38  amphtml Link Element            0 non-null      float64
 39  Size (bytes)                    1950 non-null   int64
 40  Transferred (bytes)             1950 non-null   int64
 41  Word Count                      1950 non-null   int64
 42  Sentence Count                  1564 non-null   float64
 43  Average Words Per Sentence      1564 non-null   float64
 44  Flesch Reading Ease Score       1564 non-null   float64
 45  Readability                     1564 non-null   object
 46  Text Ratio                      1950 non-null   float64
 47  Crawl Depth                     1950 non-null   int64
 48  Folder Depth                    1950 non-null   int64
 49  Link Score                      0 non-null      float64
 50  Inlinks                         1950 non-null   int64
 51  Unique Inlinks                  1950 non-null   int64
 52  Unique JS Inlinks               1950 non-null   int64
 53  % of Total                      1950 non-null   float64
 54  Outlinks                        1950 non-null   int64
 55  Unique Outlinks                 1950 non-null   int64
 56  Unique JS Outlinks              1950 non-null   int64
 57  External Outlinks               1950 non-null   int64
 58  Unique External Outlinks        1950 non-null   int64
 59  Unique External JS Outlinks     1950 non-null   int64
 60  Closest Similarity Match        0 non-null      float64
 61  No. Near Duplicates             0 non-null      float64
 62  Spelling Errors                 0 non-null      float64
 63  Grammar Errors                  0 non-null      float64
 64  Hash                            1615 non-null   object
 65  Response Time                   1903 non-null   float64
 66  Last Modified                   473 non-null    object
 67  Redirect URL                    118 non-null    object
 68  Redirect Type                   118 non-null    object
 69  Cookies                         0 non-null      float64
 70  HTTP Version                    1903 non-null   float64
 71  URL Encoded Address             1950 non-null   object
 72  Crawl Timestamp                 1950 non-null   object
 73  Meta Robots 3                   2 non-null      object
 74  Meta Robots 4                   2 non-null      object
 75  Canonical Link Element 2        10 non-null     object
 76  Meta Description 3              1 non-null      object
 77  Meta Description 3 Length       96 non-null     float64
 78  Meta Description 3 Pixel Width  96 non-null     float64
 79  Meta Keywords 2                 1 non-null      object
 80  Meta Keywords 2 Length          96 non-null     float64
dtypes: float64(23), int64(24), object(34)
memory usage: 1.2+ MB

In [ ]:
df = data[data['Status Code'] == 200]

In [ ]:
df = df[['Address' , 'Content Type' , 'Status Code' , 'Indexability', 'Title 1' , 'Title 1 Length' , 'Title 1 Pixel Width' , 'Meta Description 1' ,
        'Meta Description 1 Length' , 'Meta Description 1 Pixel Width' , 'H1-1' , 'H1-1 Length' , 'H1-2' , 'H1-2 Length' , 'Word Count' ,
        'Sentence Count' , 'Size (bytes)', 'Transferred (bytes)','Word Count', 'Sentence Count', 'Average Words Per Sentence', '% of Total' ,
        'Outlinks', 'Unique Outlinks','Unique JS Outlinks', 'External Outlinks', 'Unique External Outlinks','Unique External JS Outlinks',
        'Response Time']]

In [ ]:
regex = r'^(?!.*\b(facebook|instagram|linkedin|youtube|amazon|aliexpress|daraz|alibaba|temu|etsy|shopify|ebay|tiktok|wikipedia|reddit)\b).*$'

# Filter DataFrame
df = df[df['Address'].str.match(regex, case=False, na=False)]

In [ ]:
random_names = df['Meta Description 1'].dropna().sample(n=30, random_state=42)

In [ ]:
random_names = random_names.values

# Get the indices of the NaN values
na_indices = df[df['Meta Description 1'].isna()].index

# Fill the NaN values with random choices from random_names
df.loc[na_indices, 'Meta Description 1'] = np.random.choice(random_names, size=len(na_indices))

In [ ]:
random_names = df['Title 1'].dropna().sample(n=30, random_state=42)

In [ ]:
random_names = random_names.values

# Get the indices of the NaN values
na_indices = df[df['Title 1'].isna()].index

# Fill the NaN values with random choices from random_names
df.loc[na_indices, 'Title 1'] = np.random.choice(random_names, size=len(na_indices))

In [ ]:
import re

def fill_missing_values(df):
    heading_columns = [col for col in df.columns if re.match(r'H\d+-\d+', col)]
    print(heading_columns)

    for col in heading_columns:

        non_na_values = df[col].dropna()
        sample_size = min(30, len(non_na_values))

        sampled_values = non_na_values.sample(n=sample_size, random_state=42, replace=True).values
        missing_indices = df[df[col].isna()].index

        for idx in missing_indices:
            df.at[idx, col] = np.random.choice(sampled_values)

    return df

def update_length_columns(df):
    # Identify the heading columns using regex
    heading_columns = [col for col in df.columns if re.match(r'H\d+-\d+', col)]

    for col in heading_columns:
        length_column = col + " Length"

        df[length_column] = df[col].apply(lambda x: len(str(x)) if pd.notna(x) else np.nan)
        meta_columns = [col for col in df.columns if 'Meta Description' in col]
    for col in meta_columns:
        # Identify the corresponding length column (e.g., 'Meta Description 1 Length')
        length_column = col + " Length"
        df[length_column] = df[col].apply(lambda x: len(str(x)) if pd.notna(x) else np.nan)

    # For titles (e.g., 'Title 1', 'Title 2', etc.)
    title_columns = [col for col in df.columns if 'Title' in col]
    for col in title_columns:
        # Identify the corresponding length column (e.g., 'Title 1 Length')
        length_column = col + " Length"
        df[length_column] = df[col].apply(lambda x: len(str(x)) if pd.notna(x) else np.nan)

    return df

# Example usage
df = fill_missing_values(df)
df = update_length_columns(df)
df

['H1-1', 'H1-1 Length', 'H1-2', 'H1-2 Length']

,Address,Content Type,Status Code,Indexability,Title 1,Title 1 Length,Title 1 Pixel Width,Meta Description 1,Meta Description 1 Length,Meta Description 1 Pixel Width,...,External Outlinks,Unique External Outlinks,Unique External JS Outlinks,Response Time,H1-1 Length Length,H1-2 Length Length,Meta Description 1 Length Length,Meta Description 1 Pixel Width Length,Title 1 Length Length,Title 1 Pixel Width Length
0,https://en.cypris-online.jp/,text/html; charset=UTF-8,200,Indexable,Men's Leather Wallet CYPRIS Official Online Shop,48,436,CYPRIS official mail order for leather wallets...,281,1726,...,7,6,0,3.561,2,2,3,4,2,3
1,https://www.tannergoods.com/collections/wallets,text/html; charset=utf-8,200,Indexable,Shop Leather Wallets | Tanner Goods,35,327,A timeless wallet doesn’t need to be boring. T...,255,1547,...,7,5,0,1.046,2,2,3,4,2,3
2,https://ghurka.com/collections/leather-wallets,text/html; charset=utf-8,200,Indexable,Leather Wallets\n – Ghurka,25,223,Discover the Wooden Chair by Marc Newson craft...,135,0,...,5,5,0,0.873,2,2,3,1,2,3
3,https://www.hobobags.com/collections/sale-leat...,text/html; charset=utf-8,200,Indexable,Sale Wallets\n– HOBO,19,185,"Compact, classic and on sale! Shop our leather...",159,947,...,13,9,0,1.064,2,2,3,3,2,3
4,https://martindingman.com/collections/all-wallets,text/html; charset=utf-8,200,Indexable,Shop Luxury Leather Wallets for Men | Martin D...,52,481,The Martin Dingman wallet collection has been ...,143,867,...,2,2,0,0.998,2,1,3,3,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1944,https://www.notonthehighstreet.com/jewellery/w...,text/html; charset=utf-8,200,Indexable,Women's jewellery | Jewellery | NOTHS,39,342,Looking for ladies jewellery? With our exclusi...,115,713,...,10,8,0,2.268,2,2,3,3,2,3
1945,https://www.barts.eu/women-jewellery,text/html,200,Indexable,Women Jewellery - BARTS Official Website - Sho...,51,481,Shop your favorite Women Jewellery now at the ...,131,820,...,3,3,0,1.144,2,2,3,3,2,3
1946,https://pk.ethnc.com/collections/women-jewelle...,text/html; charset=utf-8,200,Indexable,WOMEN JEWELLERY & ACCESSORIES\n – ETHNC,38,427,Accessories are a unique expression of your pe...,196,1194,...,18,12,0,0.561,2,2,3,4,2,3
1947,https://ego.co.uk/accessories/jewellery.html,text/html; charset=UTF-8,200,Indexable,Women's Jewellery | Statement Jewellery | EGO,45,419,Take your look from basic to boujee with state...,157,980,...,9,9,0,1.171,1,2,3,3,2,3
1948,https://shop.mango.com/us/en/c/women/jewellery...,text/html; charset=utf-8,200,Indexable,Women’s jewellery 2024 | MANGO USA,34,343,Complete your look with our women's jewelry. F...,177,1073,...,13,13,0,2.631,2,2,3,4,2,3

In [ ]:
df.to_csv('dataset.csv', index=False)